"""Bid Workflow — data-driven workflow representation.

Workflows are now generated by PlannerAgent and stored as JSON, not hardcoded steps.
This allows different solicitations to have different plans.
"""
from __future__ import annotations
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Literal

import os

log = logging.getLogger(__name__)

StepStatus = Literal["pending", "in_progress", "completed", "failed", "skipped"]


@dataclass
class WorkflowStep:
    """A single step in the bid workflow (data, not code)."""
    step_id: str
    name: str
    goal: str
    success_criteria: list[str] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)
    agent_assigned: str = "bid_executor"
    tools_needed: list[str] = field(default_factory=list)
    estimated_duration_minutes: int = 30
    status: StepStatus = "pending"
    deliverable: str | None = None
    output_file: str | None = None
    completed_at: str | None = None
    error: str | None = None
    retry_count: int = 0

    def to_dict(self) -> dict:
        return {
            "step_id": self.step_id,
            "name": self.name,
            "goal": self.goal,
            "success_criteria": self.success_criteria,
            "dependencies": self.dependencies,
            "agent_assigned": self.agent_assigned,
            "tools_needed": self.tools_needed,
            "estimated_duration_minutes": self.estimated_duration_minutes,
            "status": self.status,
            "deliverable": self.deliverable,
            "output_file": self.output_file,
            "completed_at": self.completed_at,
            "error": self.error,
            "retry_count": self.retry_count
        }

    @classmethod
    def from_dict(cls, d: dict) -> "WorkflowStep":
        return cls(
            step_id=d.get("step_id", ""),
            name=d.get("name", ""),
            goal=d.get("goal", ""),
            success_criteria=d.get("success_criteria", []),
            dependencies=d.get("dependencies", []),
            agent_assigned=d.get("agent_assigned", "bid_executor"),
            tools_needed=d.get("tools_needed", []),
            estimated_duration_minutes=d.get("estimated_duration_minutes", 30),
            status=d.get("status", "pending"),
            deliverable=d.get("deliverable"),
            output_file=d.get("output_file"),
            completed_at=d.get("completed_at"),
            error=d.get("error"),
            retry_count=d.get("retry_count", 0)
        )


@dataclass
class BidWorkflow:
    """Workflow as data — generated by PlannerAgent, not hardcoded."""
    workflow_id: str | None = None
    solicitation_id: str = ""
    title: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    steps: list[WorkflowStep] = field(default_factory=list)
    current_step_index: int = 0
    total_estimated_minutes: int = 0
    risk_flags: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        if not self.workflow_id:
            import uuid
            self.workflow_id = str(uuid.uuid4())[:8]

    @classmethod
    def from_json(cls, json_str: str) -> "BidWorkflow":
        """Create workflow from JSON (output of PlannerAgent)."""
        data = json.loads(json_str)
        steps = [WorkflowStep.from_dict(s) for s in data.get("steps", [])]
        return cls(
            workflow_id=data.get("workflow_id"),
            solicitation_id=data.get("solicitation_id", ""),
            title=data.get("title", ""),
            created_at=data.get("created_at", datetime.now().isoformat()),
            steps=steps,
            total_estimated_minutes=data.get("total_estimated_minutes", 0),
            risk_flags=data.get("risk_flags", []),
            metadata=data
        )

    def to_json(self) -> str:
        """Serialize workflow to JSON."""
        return json.dumps({
            "workflow_id": self.workflow_id,
            "solicitation_id": self.solicitation_id,
            "title": self.title,
            "created_at": self.created_at,
            "steps": [s.to_dict() for s in self.steps],
            "total_estimated_minutes": self.total_estimated_minutes,
            "risk_flags": self.risk_flags,
            "metadata": self.metadata
        }, indent=2)

    def get_current_step(self) -> WorkflowStep | None:
        if 0 <= self.current_step_index < len(self.steps):
            return self.steps[self.current_step_index]
        return None

    def get_step(self, step_id: str) -> WorkflowStep | None:
        for step in self.steps:
            if step.step_id == step_id:
                return step
        return None

    def complete_step(self, deliverable: str, output_file: str | None = None):
        step = self.get_current_step()
        if step:
            step.status = "completed"
            step.deliverable = deliverable
            step.output_file = output_file
            step.completed_at = datetime.now().isoformat()
            log.info("[workflow] completed step: %s", step.step_id)

    def fail_step(self, error: str, max_retries: int = 3):
        step = self.get_current_step()
        if step:
            step.retry_count += 1
            if step.retry_count >= max_retries:
                step.status = "failed"
                step.error = error
                log.error("[workflow] failed step: %s - %s", step.step_id, error)
            else:
                step.status = "pending"
                log.warning("[workflow] retry step %s (attempt %d)", step.step_id, step.retry_count)

    def can_proceed(self) -> bool:
        return self.current_step_index < len(self.steps)

    def next_step(self):
        """Advance to next step, checking dependencies are met."""
        while self.current_step_index < len(self.steps):
            step = self.steps[self.current_step_index]
            
            deps_met = all(
                self.get_step(dep).status == "completed" 
                for dep in step.dependencies 
                if self.get_step(dep)
            )
            
            if step.status in ["pending", "skipped"] and (not step.dependencies or deps_met):
                break
            
            if step.status == "completed":
                self.current_step_index += 1
            elif step.status == "failed":
                break
            else:
                self.current_step_index += 1

    def is_complete(self) -> bool:
        return all(s.status == "completed" for s in self.steps)

    def progress(self) -> dict:
        total = len(self.steps)
        completed = sum(1 for s in self.steps if s.status == "completed")
        failed = sum(1 for s in self.steps if s.status == "failed")
        return {
            "total": total,
            "completed": completed,
            "failed": failed,
            "in_progress": sum(1 for s in self.steps if s.status == "in_progress"),
            "percentage": round(100 * completed / total, 1) if total > 0 else 0
        }

    def summary(self) -> str:
        p = self.progress()
        return f"Workflow: {self.solicitation_id} — {p['completed']}/{p['total']} steps ({p['percentage']}%)"

    def save(self, path: str):
        """Save workflow to file."""
        Path(path).write_text(self.to_json())
        log.info("[workflow] saved to: %s", path)

    @classmethod
    def load(cls, path: str) -> "BidWorkflow":
        """Load workflow from file."""
        data = json.loads(Path(path).read_text())
        steps = [WorkflowStep.from_dict(s) for s in data.get("steps", [])]
        wf = cls(
            workflow_id=data.get("workflow_id"),
            solicitation_id=data.get("solicitation_id", ""),
            title=data.get("title", ""),
            created_at=data.get("created_at"),
            steps=steps,
            total_estimated_minutes=data.get("total_estimated_minutes", 0),
            risk_flags=data.get("risk_flags", []),
            metadata=data.get("metadata", {})
        )
        wf.current_step_index = data.get("current_step_index", 0)
        return wf


def create_default_workflow(solicitation_id: str) -> BidWorkflow:
    """Create a basic workflow for when PlannerAgent isn't used.
    
    This is a fallback — the preferred path is to use PlannerAgent.
    """
    return BidWorkflow(
        solicitation_id=solicitation_id,
        title="Default Bid Response",
        steps=[
            WorkflowStep(
                step_id="1",
                name="Analyze Solicitation",
                goal="Understand requirements and identify critical sections",
                success_criteria=["All requirements identified", "Timeline clear"],
                agent_assigned="analyst",
                tools_needed=["retrieve_knowledge"]
            ),
            WorkflowStep(
                step_id="2",
                name="Compliance Audit",
                goal="Check all fail-points in the solicitation",
                success_criteria=["No missing documents", "All signatures identified"],
                dependencies=["1"],
                agent_assigned="bid_executor",
                tools_needed=["check_compliance", "retrieve_knowledge"]
            ),
            WorkflowStep(
                step_id="3",
                name="Technical Proposal Draft",
                goal="Write compliant technical proposal sections",
                success_criteria=["All sections complete", "Requirements addressed"],
                dependencies=["2"],
                agent_assigned="drafter",
                tools_needed=["retrieve_knowledge"]
            ),
            WorkflowStep(
                step_id="4",
                name="Cost/Pricing",
                goal="Prepare pricing submission",
                success_criteria=["Pricing complete", "Math verified"],
                dependencies=["3"],
                agent_assigned="strategist"
            ),
            WorkflowStep(
                step_id="5",
                name="Final Verification",
                goal="Verify responsiveness before submission",
                success_criteria=["All checks pass", "No missing items"],
                dependencies=["4"],
                agent_assigned="bid_executor",
                tools_needed=["verify_responsiveness"]
            ),
            WorkflowStep(
                step_id="6",
                name="Submit",
                goal="Upload bid to procurement portal",
                success_criteria=["Submission confirmed", "Receipt obtained"],
                dependencies=["5"],
                agent_assigned="orchestrator"
            ),
        ],
        total_estimated_minutes=180
    )